import MagicSquares.CenterOne.Geometry
import MagicSquares.CenterOne.Powers
import MagicSquares.CenterOne.Forbidden
import MagicSquares.CenterOne.BadParameters
import MagicSquares.CenterOne.MegaBatch
